config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/cms', as: 'rails_admin'
  use_doorkeeper

  root to: 'home#index'
  get 'catalog', to: 'books#index'
  get 'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put 'settings/addresses', to: 'addresses#update'
  get 'settings/privacy', to: 'users#edit'

  resources :users, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end


  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end
  resources :carts, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html




  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]


  devise_for :admins
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = Order.new(order_item_ids: session[:cart])
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_order_items.html.haml
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600 Product
    %th.col-title
    %th.col-price
      %span.in-grey-600 Price
    %th.col-quantity
      %span.in-grey-600 Quantity
    %th.col-total
      %span.in-grey-600 Subtotal
  - @order.order_items.each do |order_item|
    %tr
      %td
        .general-img-wrap-table
          = link_to books_path(order_item.book) do
            = image_tag(order_item.book.cover, class: "cart-img-shadow pull-left", alt: "design-book")
      %td
        = link_to books_path(order_item.book), class: "title-link" do
          %p.title = order_item.book.title

      %td
        %span.font-16.in-gold-500 = "$#{order_item.book.price}"
      %td
        = render 'quantity', order_item: order_item
      %td
        %span.font-16.in-gold-500 = "$#{order_item.book.price * order_item.quantity}"
      %td
        %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"}&times;

app/views/carts/_order_items_extra.html.haml
- @order.order_items.each do |order_item|
  .general-cart-close.divider-lg-bottom
    = button_to order_item, method: :delete, class: 'close general-cart-close' do
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      = link_to books_path(order_item.book) do
        = image_tag(order_item.book.cover, class: "cart-img-shadow", alt: "design-book")
    = link_to books_path(order_item.book), class: "title-link" do
      %p.title = order_item.book.title
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 = "$#{order_item.book.price}"
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          = render 'quantity', order_item: order_item
      %tr
        %td
          %span.in-grey-600 Subtotal
        %td
          %span.font-16.in-gold-500 = "$#{order_item.book.price * order_item.quantity}"

app/views/carts/_quantity.html.haml
.input-group
  = form_for order_item, method: :put do |form|
    = link_to order_item_path(id: order_item.id, order_item: {quantity: order_item.quantity - 1}), :method => :put, class: "input-link pt-7" do
      %i.fa.fa-minus.line-height-40
    = form.text_field :quantity, value: order_item.quantity, class: "form-control quantity-input"
    = link_to order_item_path(id: order_item.id, order_item: {quantity: order_item.quantity + 1}), :method => :put, class: "input-link pt-7" do
      %i.fa.fa-plus.line-height-40

app/views/carts/show.html.haml
%main.container.general-img-wrap
  %h1.general-title-margin Cart
  - items = OrderItem.where(id: session[:cart])
  - if items.empty?
    .text-center
      %p.font-18 Cart is empty
      = link_to "Go to store", catalog_path(), class: "btn btn-default mb-20"
  - else
    .visible-xs
      = render 'carts/order_items_extra'
    .hidden-xs
      = render 'order_items'
    .general-order-wrap
      .row
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18 Order Summary
            %table.general-summary-table.general-summary-table-right.general-text-right
              = render 'checkout/order_summary', order: @order
            = link_to "Checkout", checkout_path(:login), class: "btn btn-default mb-20 visible-xs-inline-block"
    .text-center
      = link_to "Checkout", checkout_path(:login), class: "btn btn-default mb-20 hidden-xs"