config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/cms', as: 'rails_admin'
  use_doorkeeper

  root to: 'home#index'
  get 'catalog', to: 'books#index'
  get 'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put 'settings/addresses', to: 'addresses#update'
  get 'settings/privacy', to: 'users#edit'

  resources :users, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end


  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end
  resources :carts, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html




  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]


  devise_for :admins
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_order



  protected

  def afrer_sign_in_path_for(resource)
    if cookies[:from_checkout]
      cookies.delete :from_checkout
      checkout_path(:addresses)
    else
      super
    end
  end
=begin
  def after_sign_in_path_for(resource)
    if request.env['omniauth.origin']
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    else
      sign_in_url = new_user_session_url
      if request.referer == sign_in_url
        super
      else
        stored_location_for(resource) || request.referer || root_path
      end
    end
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end
=end

  private


  def current_order
    return Order.new unless session[:order_id]
    Order.find(session[:order_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def categories
    Category.order('name')
  end

  def cart_items_count
    return OrderItem.where(id: session[:cart]).sum(:quantity) if session[:cart]
    current_order.order_items.sum(:quantity)
  end

  def number_to_dollar(amount)
    number_to_currency(amount, unit: '$')
  end
end

app/views/application/_alerts.haml
%section
  .container
    -flash.each do |type, message|
      .alert.alert-dismissible{:class => "alert-#{type}"}
        %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close"} &times;
        = message

app/views/application/_footer.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to "Home", root_path, class: "nav-link"
          %li
            %a.nav-link{href: "#"} Shop
          - if user_signed_in?
            %li
              = link_to "Orders", orders_path, class: "nav-link"
            %li
              = link_to "Settings", settings_addresses_path, class: "nav-link"
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number 8-(800)-555-35-35
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/application/_header.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Bookstore
      %a.shop-link.pull-right.visible-xs{href: cart_path}
        = render 'shop_icon'
    %a.shop-link.pull-right.hidden-xs{href: cart_path}
      = render 'shop_icon'
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li
            = link_to "Home", orders_path
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "#menu", 'aria-expanded': "false", 'aria-controls': "menu"} Shop
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}

              - categories.each do |category|
                %li
                  = link_to "#{category.name}", catalog_path(category_id: category.id), class: "collapse-link"
          - if user_signed_in?
            %li
              %a{type: "button", 'data-toggle': "collapse", href: "#menu_my_account", 'aria-expanded': "false", 'aria-controls': "menu_my_account"} My account
              %ul#menu_my_account.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
                %li
                  =link_to "Orders", orders_path, class: "collapse-link"
                %li
                  =link_to "Settings", settings_addresses_path, class: "collapse-link"
            %li
              =link_to "Log out", destroy_user_session_path, method: :delete
          - else
            %li
              =link_to "Log in", new_user_session_path
            %li
              =link_to "Sign up", new_user_registration_path
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            =link_to "Home", root_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"} Shop
            %ul.dropdown-menu
              - categories.each do |category|
                %li
                  = link_to "#{category.name}", catalog_path(category_id: category.id)
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"} My account
              %ul.dropdown-menu
                %li
                  = link_to "Orders", root_path
                %li
                  = link_to "Settings", settings_addresses_path
                %li.divider{role: "separator"}
                %li
                  =link_to "Log out", destroy_user_session_path, method: :delete
          - else
            %li
              =link_to "Log in", new_user_session_path
            %li
              =link_to "Sign up", new_user_registration_path

app/views/application/_shop_icon.haml
- items_count = cart_items_count
- if items_count > 0
  %span.shop-icon
    %span.shop-quantity = items_count
- else
  %span.shop-icon